# https://gitea.com/gitea/helm-gitea
repositories:
  - name: argo
    url: https://argoproj.github.io/argo-helm
releases:
  - name: gitea
    namespace: argocd
    chart: argo/argocd-apps
    version: 2.0.4
    values:
      - applications:
          gitea:
            project: default
            source:
              repoURL: https://dl.gitea.com/charts/
              chart: gitea
              targetRevision: "*"
              helm:
                values: |
                  gitea:
                    admin:
                      username: "admin"
                      password: "admin"
                      email: "gi@tea.com"
                    metrics:
                      enabled: true
                  ingress:
                    enabled: false
                  deployment:
                    env:
                      # Will be automatically defined!
                      - name: GOMAXPROCS
                        valueFrom:
                          resourceFieldRef:
                            divisor: "1" # Is required for GitDevOps systems like ArgoCD/Flux. Otherwise throw the system a diff error. (k8s-default=1)
                            resource: limits.cpu

                  resources:
                    limits:
                      cpu: 1000m
                      memory: 512Mi
                    requests:
                      cpu: 100m
                      memory: 512Mi
            destination:
              name: in-cluster
              namespace: gitea
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions:
                - CreateNamespace=true
      - applications:
          gitea-ingress:
            project: default
            source:
              repoURL: https://charts.helm.sh/incubator
              chart: raw
              targetRevision: "*"
              helm:
                values: |
                  resources:
                    - apiVersion: traefik.io/v1alpha1
                      kind: IngressRoute
                      metadata:
                        name: gitea
                        namespace: gitea
                      spec:
                        entryPoints:
                          - web
                        routes:
                          - kind: Rule
                            match: Host(`git.localhost`)
                            priority: 10
                            services:
                              - name: gitea-http
                                port: 3000
            destination:
              name: in-cluster
              namespace: gitea
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions:
                - CreateNamespace=true
