---
# Source: argocd-apps/templates/applications.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
spec:
  project: default
  source:
    chart: gitea
    helm:
      values: |
        gitea:
          admin:
            username: "admin"
            password: "admin"
            email: "gi@tea.com"
          metrics:
            enabled: true
        ingress:
          enabled: false
        deployment:
          env:
            # Will be automatically defined!
            - name: GOMAXPROCS
              valueFrom:
                resourceFieldRef:
                  divisor: "1" # Is required for GitDevOps systems like ArgoCD/Flux. Otherwise throw the system a diff error. (k8s-default=1)
                  resource: limits.cpu
    
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 512Mi
    repoURL: https://dl.gitea.com/charts/
    targetRevision: '*'
  destination:
    name: in-cluster
    namespace: gitea
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
# Source: argocd-apps/templates/applications.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea-ingress
spec:
  project: default
  source:
    chart: raw
    helm:
      values: |
        resources:
          - apiVersion: traefik.io/v1alpha1
            kind: IngressRoute
            metadata:
              name: gitea
              namespace: gitea
            spec:
              entryPoints:
                - web
              routes:
                - kind: Rule
                  match: Host(`git.localhost`)
                  priority: 10
                  services:
                    - name: gitea-http
                      port: 3000
    repoURL: https://charts.helm.sh/incubator
    targetRevision: '*'
  destination:
    name: in-cluster
    namespace: gitea
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
