# https://docs.grafana.com/charts/installation/deployment/
repositories:
  - name: argo
    url: https://argoproj.github.io/argo-helm

releases:
  - name: grafana
    namespace: argocd
    chart: argo/argocd-apps
    version: 2.0.4
    values:
      - applications:
          grafana:
            project: default
            source:
              repoURL: https://grafana-community.github.io/helm-charts
              chart: grafana
              targetRevision: "*"
              helm:
                values: |
                  # x
            destination:
              name: in-cluster
              namespace: grafana
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions:
                - CreateNamespace=true
      - applications:
          grafana-ingress:
            project: default
            source:
              repoURL: https://charts.helm.sh/incubator
              chart: raw
              targetRevision: "*"
              helm:
                values: |
                  resources:
                    - apiVersion: traefik.io/v1alpha1
                      kind: IngressRoute
                      metadata:
                        name: grafana
                        namespace: grafana
                      spec:
                        entryPoints:
                          - web
                        routes:
                          - kind: Rule
                            match: Host(`grafana.localhost`)
                            priority: 10
                            services:
                              - name: grafana
                                port: 80
            destination:
              name: in-cluster
              namespace: grafana
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions:
                - CreateNamespace=true