---
# Source: argocd-apps/templates/applications.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
spec:
  project: default
  source:
    chart: traefik
    helm:
      values: |
        ingressRoute:
          dashboard:
            enabled: true
            matchRule: Host(`dashboard.localhost`)
            entryPoints:
              - web
        providers:
          kubernetesGateway:
            enabled: true
        gateway:
          listeners:
            web:
              namespacePolicy:
                from: All
    repoURL: https://traefik.github.io/charts
    targetRevision: '*'
  destination:
    name: in-cluster
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
