repositories:
  - name: argo
    url: https://argoproj.github.io/argo-helm

releases:
  - name: traefik-app
    namespace: argocd
    chart: argo/argocd-apps
    version: 2.0.4
    values:
      - applications:
          traefik:
            project: default
            source:
              repoURL: https://traefik.github.io/charts
              chart: traefik
              targetRevision: "*"
              helm:
                values: |
                  ingressRoute:
                    dashboard:
                      enabled: true
                      matchRule: Host(`dashboard.localhost`)
                      entryPoints:
                        - web
                  providers:
                    kubernetesGateway:
                      enabled: true
                  gateway:
                    listeners:
                      web:
                        namespacePolicy:
                          from: All
            destination:
              name: in-cluster
              namespace: kube-system
            syncPolicy:
              automated:
                prune: true
                selfHeal: true