repositories:
  - name: argo
    url: https://argoproj.github.io/argo-helm
  - name: incubator
    url: https://charts.helm.sh/incubator

releases:
  - name: traefik-app
    namespace: argocd
    chart: argo/argocd-apps
    version: 2.0.4
    values:
      - applications:
          traefik:
            project: default
            source:
              repoURL: https://traefik.github.io/charts
              chart: traefik
              targetRevision: "*"
              helm:
                values: |
                  ingressRoute:
                    dashboard:
                      enabled: true
                      matchRule: Host(`traefik.localhost`)
                      entryPoints:
                        - web
                  providers:
                    kubernetesGateway:
                      enabled: true
                  gateway:
                    listeners:
                      web:
                        namespacePolicy:
                          from: All
            destination:
              name: in-cluster
              namespace: kube-system
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions:
                - CreateNamespace=true
      - applications:
          argocd-ingress:
            project: default
            source:
              repoURL: https://charts.helm.sh/incubator
              chart: raw
              targetRevision: "*"
              helm:
                values: |
                  resources:
                  - apiVersion: traefik.io/v1alpha1
                    kind: IngressRoute
                    metadata:
                      name: argocd-server
                      namespace: argocd
                    spec:
                      entryPoints:
                        - web
                      routes:
                        - kind: Rule
                          match: Host(`argocd.localhost`)
                          priority: 10
                          services:
                            - name: argocd-server
                              port: 80
            destination:
              name: in-cluster
              namespace: argocd
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions:
                - CreateNamespace=true