# https://docs.opentelemetry.com/charts/installation/deployment/
repositories:
  - name: argo
    url: https://argoproj.github.io/argo-helm

releases:
  - name: opentelemetry
    namespace: argocd
    chart: argo/argocd-apps
    version: 2.0.4
    values:
      - applications:
          opentelemetry:
            project: default
            source:
              repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
              chart: opentelemetry-kube-stack
              targetRevision: "*"
              helm:
                values: |
                  opentelemetry-operator:
                    admissionWebhooks:
                      certManager:
                        enabled: false
                      autoGenerateCert:
                        enabled: true
                  collectors:
                    daemon:
                      # disable Prometheus scrapping
                      presets:
                        logsCollection:
                          enabled: true
                        kubeletMetrics:
                          enabled: true
                        hostMetrics:
                          enabled: true
                        kubernetesAttributes:
                          enabled: true
                        kubernetesEvents:
                          enabled: true
                        clusterMetrics:
                          enabled: true
                        annotationDiscovery:
                          logs:
                            enabled: true
                          metrics:
                            enabled: true
            destination:
              name: in-cluster
              namespace: opentelemetry
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions:
                - CreateNamespace=true